[package]
name = "rastermind"
version = "0.6.19"
authors = ["mandeep <mandeep@users.noreply.github.com>"]

[dependencies]
image = "0.21.0"
nalgebra = "0.19.0"

[profile.dev]
opt-level = 2
debug = true
incremental = true
overflow-checks = false
