[package]
name = "rastermind"
version = "0.6.20"
authors = ["mandeep <mandeep@users.noreply.github.com>"]

[dependencies]
image = "0.22"
nalgebra = "0.19"

[profile.dev]
opt-level = 2
debug = true
incremental = true
overflow-checks = false
